### ISSUE TITLE
Post editor PHP warning: Header already sent

### ISSUE THREAD

**Issue by carolinan** [aristath/q#12]
I added a navigation block in the post editor, and got the following warning:
`
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/themes/q/includes/BlockStyles.php:63) in /var/www/html/wp-admin/admin-header.php on line 9`

When I view source, I see that the style is printed in the wrong place:

```
<style>.wp-block-navigation:not(.has-background) .wp-block-navigation__container .wp-block-navigation-link:not(.has-text-color) { /* stylelint-disable-line selector-class-pattern */
	color: currentColor;
}
</style>
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/themes/q/includes/BlockStyles.php:63) in /var/www/html/wp-admin/admin-header.php on line 9
<!DOCTYPE html>
<html class="wp-toolbar"
	lang="en-US">
<head>
```

( using the theme version from github not the directory)

**Comment by aristath** [comment]
Hmmm I this using the stable version of Gutenberg as well as the master branch in WP 5.6-RC4, and I could not replicate it.
Am I missing a step? I tried in the new-post screen, in the template-edit screen as well as the site-editor :thinking:
