### ISSUE TITLE
🧹 De-clutter theme root directory

### ISSUE THREAD

**Issue by szepeviktor** [aristath/q#7]
Did you know that WordPress core automatically recognizes themes in subdirectories?
So all WP fuss can live in a separate _box:_ `/theme` :)

Existing users have to switch forth and back to reactivate q :(

**Comment by szepeviktor** [comment]
# 🎉 

![kép](https://user-images.githubusercontent.com/952007/96368444-2031ed00-1154-11eb-8d3f-fa28e3f24378.png)

https://github.com/szepeviktor/q/tree/subDir

**Comment by seothemes** [comment]
@szepeviktor you also need to update directory paths in your fork

**Comment by szepeviktor** [comment]
Yes. I do not know where :)

May I leave it up to you?

**Comment by seothemes** [comment]
Yeah, I can do it if @aristath thinks it's worth it.

**Comment by aristath** [comment]
The fact that WP recognizes themes in sub-directories doesn't make it good practice, and there have been lots of issues in the Gutenberg editor with subdirectory themes.
The development files are not included in the releases, so I don't really see how this would benefit anyone... 
Besides we can't really change the structure now, existing sites using the theme would break.
